### ISSUE TITLE
Does Not build in Arduino IDE 2.3.2 OTA Arduino Server Example

### ISSUE THREAD

**Issue by DrSimgear** [arduino-libraries/Arduino_ESP32_OTA#38]
![image](https://github.com/user-attachments/assets/6f17c63f-39bf-49ed-90be-331d7c79a4fe)

**Comment by per1234** [comment]
Hi @DrSimgear. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
